// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../client/models.js";

/**
 * @returns {$CancellablePromise<(client$0.Client | null)[]>}
 */
export function GetClient() {
    return $Call.ByID(2808956709).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetReadPacketNum() {
    return $Call.ByID(3419017966);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetSendPacketNum() {
    return $Call.ByID(3477270852);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetClientInfo(name) {
    return $Call.ByID(2735798945, name);
}

// Private type creation functions
const $$createType0 = client$0.Client.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
