// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as client$0 from "../client/models.js";

export function GetClient(): $CancellablePromise<(client$0.Client | null)[]> {
    return $Call.ByID(2808956709).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetReadPacketNum(): $CancellablePromise<number> {
    return $Call.ByID(3419017966);
}

export function GetSendPacketNum(): $CancellablePromise<number> {
    return $Call.ByID(3477270852);
}

export function SetClientInfo(name: string): $CancellablePromise<void> {
    return $Call.ByID(2735798945, name);
}

// Private type creation functions
const $$createType0 = client$0.Client.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
