// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Client 表示虚拟网络中的客户端
 */
export class Client {
    /**
     * Creates a new Client instance.
     * @param {Partial<Client>} [$$source = {}] - The source object to create the Client.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("latency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latency"] = 0;
        }
        if (!("virtualIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["virtualIp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Client instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Client}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Client(/** @type {Partial<Client>} */($$parsedSource));
    }
}
