// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Client 表示虚拟网络中的客户端
 */
export class Client {
    "name": string;
    "latency": number;
    "virtualIp": string;

    /** Creates a new Client instance. */
    constructor($$source: Partial<Client> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("latency" in $$source)) {
            this["latency"] = 0;
        }
        if (!("virtualIp" in $$source)) {
            this["virtualIp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Client instance from a string or object.
     */
    static createFrom($$source: any = {}): Client {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Client($$parsedSource as Partial<Client>);
    }
}
